# Change these first
owner: Manu-Devloo # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Personal site
    url: https://www.manudevloo.com
    expectedStatusCodes:
      - 403
  - name: Immich
    url: https://immich.manudevloo.com
  - name: Nextcloud
    url: https://nextcloud.manudevloo.com
  - name: Jellyfin
    url: https://jellyfin.manudevloo.com
  - name: Jellyseer
    url: https://request.manudevloo.com
    expectedStatusCodes:
      - 403
  - name: QBittorrent
    url: https://torrent.manudevloo.com
    expectedStatusCodes:
      - 403
  - name: Open webui
    url: https://chat.manudevloo.com
    expectedStatusCodes:
      - 403
  - name: Audiobookshelf
    url: https://audiobookshelf.manudevloo.com
    expectedStatusCodes:
      - 403
  - name: Books
    url: https://books.manudevloo.com
    expectedStatusCodes:
      - 403
  - name: File manager
    url: https://file.manudevloo.com
    expectedStatusCodes:
      - 403
  - name: Dashboard
    url: https://flame.manudevloo.com
    expectedStatusCodes:
      - 403

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.manudevloo.com
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: Uptime of Selfhosted services
  introMessage: The uptime of Manu Devloo's resources
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
